### ISSUE TITLE
Better functional documentation?

### ISSUE THREAD

**Issue by mperham** [andersondias/sidekiq_mailer#11]
I don't understand what value this gem offers over Sidekiq itself.  Sidekiq allows you to send emails asynchronously out of the box:

https://github.com/mperham/sidekiq/wiki/Delayed-Extensions#actionmailer

Could you expand the README to document why someone would use this gem?

**Comment by andersondias** [comment]
Hello @mperham! My goal with this gem is to use sidekiq in actionmailer without changing the external API of ActionMailer.

Instead of looking for places where I need to change my ActiveMailer::Base calls to use a delayed call (Mailer.delay.mail_method), I prefer to change the Mailer class without touching it's external interface.

It does not covers all usages of delayed extension by the way, like delay_for and delay_until. It's just another way to use the delay method.

**Comment by mperham** [comment]
Cool, thanks.
